name: Crowdin  download Action

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  download-crowdin-exo:
    name: CI Build
    uses: exoplatform/swf-scripts/.github/workflows/download-crowdin-exoplatform.yml@master
    with:
      CROWDIN_DEVELOP_VERSION: ${{ vars.CROWDIN_DEVELOP_VERSION }}
      CROWDIN_MAINTENANCE_EXO_VERSION: ${{ vars.CROWDIN_MAINTENANCE_EXO_VERSION }}
    secrets:
      CROWDIN_GITHUB_TOKEN: ${{ secrets.CROWDIN_GITHUB_TOKEN }}
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}