name: Crowdin Upload main

on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  download-crowdin-exo:
    name: CI Build
    uses: exoplatform/swf-scripts/.github/workflows/upload-crowdin-main.yml@ADD_CROWDIN_WF
    secrets:
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}