name: Crowdin Upload branches

on:
  workflow_dispatch:
  push:
    branches:
      - stable/*
jobs:
  download-crowdin-exo:
    name: CI Build
    uses: exoplatform/swf-scripts/.github/workflows/download-crowdin-branches.yml@ADD_CROWDIN_WF
    with:
      CROWDIN_MAINTENANCE_BRANCH_VERSION: ${{ vars.CROWDIN_MAINTENANCE_BRANCH_VERSION }}
    secrets:
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}